#!/usr/bin/env bash

# General
alias c="clear"




# brew
alias buu="brew update && brew upgrade"



# Soft
alias mc="mc --nosubshell"


# ---- Bat (better cat) ----
if type bat &>/dev/null; then
	alias cat=bat
fi


# ---- Eza (better ls) ----
if type eza &>/dev/null; then
	alias l="eza --icons"
	alias ls="eza --icons"
	alias ll="eza -lagh --icons"
	alias la="eza -lag --icons"
	alias lt="eza -lTg --icons"
	alias lt1="eza -lTg --level=1 --icons"
	alias lt2="eza -lTg --level=2 --icons"
	alias lt3="eza -lTg --level=3 --icons"
	alias lta="eza -lTag --icons"
	alias lta1="eza -lTag --level=1 --icons"
	alias lta2="eza -lTag --level=2 --icons"
	alias lta3="eza -lTag --level=3 --icons"
fi

# ---- nvim ----
if type nvim &>/dev/null; then
	alias vim="nvim"
	alias vi="nvim"
	alias n="nvim"

  export EDITOR=nvim
  export VISUAL="$EDITOR"

fi
