setopt prompt_subst
setopt autocd
setopt interactivecomments
setopt no_beep

setopt append_history
setopt inc_append_history
setopt share_history
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_ignore_all_dups
setopt hist_find_no_dups
setopt hist_reduce_blanks
setopt hist_verify

setopt auto_pushd
setopt pushd_ignore_dups
setopt pushd_silent

setopt extendedglob